name: Challenge 1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run_challenge_1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Test
      run: |
        python challenge1_tests.py
    - name: Run
      run: |
        python challenge1.py
